### PR TITLE
Update PiGatewaySerial.cpp

### PR DESCRIPTION
**Pull request by GertSanders**

### CODE REVIEW

**Comment by henrikekblad** [comment]
Nice. thank you!

**Comment by fallberg** [comment]
Feel free to call me "gitler" but please use more descriptive commit headlines. The commit line says nothing about what has really changed.

**Comment by henrikekblad** [comment]
close #17 

https://github.com/mysensors/Raspberry/issues/17

**Comment by GertSanders** [comment]
Also the documentation regarding the pins used should be changed in the readme.md file:

For the Raspberry Pi 2 and the B with BPlus header, the documentation mentions that pin 15 should be used for CE. This does not really make sense, because pin 22 is perfectly fine as a CE pin.

GND	  25
VCC	  17
CE	  15 ----> change this to 22 (same as in the older GPIO layout).
CSN   24
SCK   23
MOSI  19
MISO  21
IRQ	  --

Regarding IRQ, this could be connected to pin 18 on the new 40 pin header, because there is a GPIO definition for this pin: GPIO 24. This can then be used in an interupt driven implementation (saw a reference to that effect somewhere, lost the link though).

**Comment by fallberg** [comment]
This is an excellent guide to good git commit messages:
http://chris.beams.io/posts/git-commit

Essentially; be descriptive, but keep headline short and put any detailed information in the "body".

**Pull request merged**
